const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0D0D0D" },
  postCard: {
    backgroundColor: "#161616",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
  },
  postHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  avatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  userMeta: { flex: 1 },
  nameRow: { flexDirection: "row", alignItems: "center" },
  displayName: { color: "#FFFFFF", fontWeight: "700", fontSize: 16 },
  timeDot: { color: "#71767b", fontSize: 14 },
  handle: { color: "#A0A0A0", fontSize: 14, marginTop: 2 },
  content: { color: "#FFFFFF", fontSize: 16, lineHeight: 22, marginBottom: 12 },
  postImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: "#262626",
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 8,
  },
  actionItem: { flexDirection: "row", alignItems: "center" },
  actionText: { color: "#A0A0A0", marginLeft: 6, fontSize: 14 },
  fab: {
    position: "absolute",
    bottom: 30,
    right: 20,
    backgroundColor: "#7D7AFF", // That specific light purple/blue
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowRadius: 10,
    shadowOpacity: 0.5,
  },
  pill: {
    position: "absolute",
    top: 60,
    alignSelf: "center",
    backgroundColor: "#7D7AFF",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    zIndex: 100,
  },
  pillText: { color: "white", fontWeight: "bold" },
});
